version: '3.9'

services:
  postgresdb:
    image: postgres:latest
    container_name: postgresql-auth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin      # Remplacez par le nom d'utilisateur souhaité
      POSTGRES_PASSWORD: adminpwd  # Remplacez par le mot de passe souhaité
      POSTGRES_DB: auth   # Remplacez par le nom de la base de données souhaité
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d auth"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
    #volumes:
      #- postgresql-db:/var/lib/postgresql/data

#volumes:
  #postgresql-db:

# Pour tester que la db fonctionne :
# psql -h localhost -p 5432 -U admin -d auth
